name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Checkout with submodules
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: true

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #       with:
  #         platforms: linux/amd64, linux/arm64

  #     - name: Build
  #       uses: docker/build-push-action@v6
  #       with:
  #         platforms: linux/amd64, linux/arm64
  #         context: .
  #         file: Dockerfile-starlink
  #         load: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/leoviz:starlink

  #     - name: Test
  #       working-directory: ./tests
  #       run: bash run-tests.sh

  build:
    # needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          context: .
          file: Dockerfile-starlink
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/leoviz:starlink

      - name: Create GitHub release
        uses: goreleaser/goreleaser-action@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
