name: test

on:
  pull_request:
    branches:
      - master
  push:
    paths:
      - '**.py'
    tags:
      - v*
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: Dockerfile-starlink
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/leoviz:starlink

      - name: Test
        working-directory: ./tests
        run: bash run-tests.sh
